### ISSUE TITLE
FedExample

### ISSUE THREAD

**Issue by amin-samadi-khoshkho** [zfscgy/Amber#1]
Hi,
I am trying to use [FedExample] (https://github.com/zfscgy/Amber/tree/master/Examples/FedExample), specifically FedDNN784_128_10, but I get different errors. Could you please provide some explanation about how to run the code? I want to run it on my own device.

Thanks

**Comment by zfscgy** [comment]
Hello, I examined the code again and fixed some minor bugs regarding to my current numpy version. Now I can run it on my machine. The fed_dnn0.py's log is like
```
player0: data read finished
Round 0 Acc 0.1218
Round 0 train loss: 0.289
Round 1 train loss: 0.269
Round 2 train loss: 0.244
Round 3 train loss: 0.238
Round 4 train loss: 0.234
Round 5 train loss: 0.225
Round 6 train loss: 0.217
Round 7 train loss: 0.208
Round 8 train loss: 0.206
Round 9 train loss: 0.198
...
```

To run the example, you need to run the three scripts (fed_dnn0.py, fed_dnn1.py, fed_dnn2.py) at the same time. If you still encounter any error, please provide me with the detailed error information, thanks!

**Comment by amin-samadi-khoshkho** [comment]
Thank you so much. It worked.😀
However, sometimes the following warnings. appear, which I hope not to be important.

<img width="1420" alt="Screenshot 2023-04-24 at 09 29 51" src="https://user-images.githubusercontent.com/82457268/234044393-9228f9f4-67b0-45be-a4e2-f1c8bb413a1f.png">

**Comment by zfscgy** [comment]
> Thank you so much. It worked.😀 However, sometimes the following warnings. appear, which I hope not to be important.
> 
> <img alt="Screenshot 2023-04-24 at 09 29 51" width="1420" src="https://user-images.githubusercontent.com/82457268/234044393-9228f9f4-67b0-45be-a4e2-f1c8bb413a1f.png">

I cannot replicate this error. However, it seems that the error 'mean of empty slice“ is caused by zero test samples. Have you modified the run_dnn file?

**Comment by TY-cc** [comment]
Hi，it report error when i run the Fedexample
![image](https://github.com/user-attachments/assets/eeabbbf1-c5ea-441e-bd24-12f74d14a9b3)
I didn't modify any code. How to solve this problem？Thanks！

**Comment by TY-cc** [comment]
i solve this problem by replace numpy-2.0.0 to numpy-1.21.5
