### ISSUE TITLE
Report the “Amber-master/Examples/Data/Datasets/gisette/gisette_train.data not found.”

### ISSUE THREAD

**Issue by TY-cc** [zfscgy/Amber#2]
It report the “Data/Datasets/gisette/gisette_train.data not found” error when i run the  Amber-master/Examples/LocalExample/lr_5000_1.py

**Comment by zfscgy** [comment]
You have to download the dataset manually from  https://archive.ics.uci.edu/dataset/170/gisette

**Comment by TY-cc** [comment]
thanks
